octopub-frontend:
  overrideTheme: green
  productEndpointOverride: /development/api/products
  ingress:
    enabled: true
  hosts:
    - host:
      paths:
        - path: /development
          pathType: Prefix