apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: octopub-frontend-application
  annotations:
    codefresh.io/product: octopub-frontend
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  destination:
    name: in-cluster
    namespace: octopub-frontend-production
  source:
    path: octopub/frontend/production
    repoURL: https://github.com/mcasperson/OctopubSampleDeployments.git
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false